export * from './aCLs.service';
import { ACLsService } from './aCLs.service';
export * from './aclResolving.service';
import { AclResolvingService } from './aclResolving.service';
export * from './controllers.service';
import { ControllersService } from './controllers.service';
export * from './doors.service';
import { DoorsService } from './doors.service';
export * from './keys.service';
import { KeysService } from './keys.service';
export * from './personnel.service';
import { PersonnelService } from './personnel.service';
export * from './places.service';
import { PlacesService } from './places.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './security.service';
import { SecurityService } from './security.service';
export const APIS = [ACLsService, AclResolvingService, ControllersService, DoorsService, KeysService, PersonnelService, PlacesService, RolesService, SecurityService];
