/**
 * Jointbox access API
 * This is a API for access management for jointbox project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dmitriy.selischev@logicify.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AllControllersResponse } from '../model/allControllersResponse';
import { AllDoorsResponse } from '../model/allDoorsResponse';
import { AllResolvedAclResponse } from '../model/allResolvedAclResponse';
import { ControllerInDto } from '../model/controllerInDto';
import { ControllerResponse } from '../model/controllerResponse';
import { EmptyOkResponse } from '../model/emptyOkResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ControllersService {

    protected basePath = 'http://jbaccess-server.herokuapp.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * attach door to a controller. Requires auth
     * 
     * @param controllerId 
     * @param doorId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public attachDoorToController(controllerId: number, doorId: number, observe?: 'body', reportProgress?: boolean): Observable<EmptyOkResponse>;
    public attachDoorToController(controllerId: number, doorId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmptyOkResponse>>;
    public attachDoorToController(controllerId: number, doorId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmptyOkResponse>>;
    public attachDoorToController(controllerId: number, doorId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (controllerId === null || controllerId === undefined) {
            throw new Error('Required parameter controllerId was null or undefined when calling attachDoorToController.');
        }

        if (doorId === null || doorId === undefined) {
            throw new Error('Required parameter doorId was null or undefined when calling attachDoorToController.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<EmptyOkResponse>(`${this.basePath}/controllers/${encodeURIComponent(String(controllerId))}/doors/${encodeURIComponent(String(doorId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * create new controller. Requires auth
     * 
     * @param controller 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createController(controller?: ControllerInDto, observe?: 'body', reportProgress?: boolean): Observable<ControllerResponse>;
    public createController(controller?: ControllerInDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ControllerResponse>>;
    public createController(controller?: ControllerInDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ControllerResponse>>;
    public createController(controller?: ControllerInDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ControllerResponse>(`${this.basePath}/controllers`,
            controller,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * delete controller but not delete attached doors. Requires auth
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteController(id: number, observe?: 'body', reportProgress?: boolean): Observable<EmptyOkResponse>;
    public deleteController(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmptyOkResponse>>;
    public deleteController(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmptyOkResponse>>;
    public deleteController(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteController.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<EmptyOkResponse>(`${this.basePath}/controllers/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * detach door from a controller. Requires auth
     * 
     * @param controllerId 
     * @param doorId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public detachDoorFromController(controllerId: number, doorId: number, observe?: 'body', reportProgress?: boolean): Observable<EmptyOkResponse>;
    public detachDoorFromController(controllerId: number, doorId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmptyOkResponse>>;
    public detachDoorFromController(controllerId: number, doorId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmptyOkResponse>>;
    public detachDoorFromController(controllerId: number, doorId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (controllerId === null || controllerId === undefined) {
            throw new Error('Required parameter controllerId was null or undefined when calling detachDoorFromController.');
        }

        if (doorId === null || doorId === undefined) {
            throw new Error('Required parameter doorId was null or undefined when calling detachDoorFromController.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<EmptyOkResponse>(`${this.basePath}/controllers/${encodeURIComponent(String(controllerId))}/doors/${encodeURIComponent(String(doorId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * gets all controllers
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllControllers(observe?: 'body', reportProgress?: boolean): Observable<AllControllersResponse>;
    public getAllControllers(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllControllersResponse>>;
    public getAllControllers(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllControllersResponse>>;
    public getAllControllers(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllControllersResponse>(`${this.basePath}/controllers`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get controller info by id
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getController(id: number, observe?: 'body', reportProgress?: boolean): Observable<ControllerResponse>;
    public getController(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ControllerResponse>>;
    public getController(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ControllerResponse>>;
    public getController(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getController.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ControllerResponse>(`${this.basePath}/controllers/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get all doors attached to controller
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDoorsByController(id: number, observe?: 'body', reportProgress?: boolean): Observable<AllDoorsResponse>;
    public getDoorsByController(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllDoorsResponse>>;
    public getDoorsByController(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllDoorsResponse>>;
    public getDoorsByController(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getDoorsByController.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllDoorsResponse>(`${this.basePath}/controllers/${encodeURIComponent(String(id))}/doors`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * resolve ACLs at the unique format
     * 
     * @param controllerId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public resolveACLs(controllerId: string, observe?: 'body', reportProgress?: boolean): Observable<AllResolvedAclResponse>;
    public resolveACLs(controllerId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllResolvedAclResponse>>;
    public resolveACLs(controllerId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllResolvedAclResponse>>;
    public resolveACLs(controllerId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (controllerId === null || controllerId === undefined) {
            throw new Error('Required parameter controllerId was null or undefined when calling resolveACLs.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllResolvedAclResponse>(`${this.basePath}/controllers/${encodeURIComponent(String(controllerId))}/resolve-acls`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update controller info. Requires auth
     * 
     * @param id 
     * @param controllerDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateController(id: number, controllerDto?: ControllerInDto, observe?: 'body', reportProgress?: boolean): Observable<ControllerResponse>;
    public updateController(id: number, controllerDto?: ControllerInDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ControllerResponse>>;
    public updateController(id: number, controllerDto?: ControllerInDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ControllerResponse>>;
    public updateController(id: number, controllerDto?: ControllerInDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateController.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<ControllerResponse>(`${this.basePath}/controllers/${encodeURIComponent(String(id))}`,
            controllerDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
