/**
 * Jointbox access API
 * This is a API for access management for jointbox project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dmitriy.selischev@logicify.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AllKeysResponse } from '../model/allKeysResponse';
import { AllPersonAclsResponse } from '../model/allPersonAclsResponse';
import { AllPersonnelResponse } from '../model/allPersonnelResponse';
import { AllRolesResponse } from '../model/allRolesResponse';
import { EmptyOkResponse } from '../model/emptyOkResponse';
import { PersonAclResponse } from '../model/personAclResponse';
import { PersonInDto } from '../model/personInDto';
import { PersonResponse } from '../model/personResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PersonnelService {

    protected basePath = 'http://jbaccess-server.herokuapp.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * add allow rule to place for person
     * 
     * @param personId 
     * @param placeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public allowPlaceForPerson(personId: number, placeId: number, observe?: 'body', reportProgress?: boolean): Observable<PersonAclResponse>;
    public allowPlaceForPerson(personId: number, placeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonAclResponse>>;
    public allowPlaceForPerson(personId: number, placeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonAclResponse>>;
    public allowPlaceForPerson(personId: number, placeId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling allowPlaceForPerson.');
        }

        if (placeId === null || placeId === undefined) {
            throw new Error('Required parameter placeId was null or undefined when calling allowPlaceForPerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<PersonAclResponse>(`${this.basePath}/person/${encodeURIComponent(String(personId))}/allow/${encodeURIComponent(String(placeId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * attach role to person
     * 
     * @param personId 
     * @param roleId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public attachRoleToPerson(personId: number, roleId: number, observe?: 'body', reportProgress?: boolean): Observable<EmptyOkResponse>;
    public attachRoleToPerson(personId: number, roleId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmptyOkResponse>>;
    public attachRoleToPerson(personId: number, roleId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmptyOkResponse>>;
    public attachRoleToPerson(personId: number, roleId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling attachRoleToPerson.');
        }

        if (roleId === null || roleId === undefined) {
            throw new Error('Required parameter roleId was null or undefined when calling attachRoleToPerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<EmptyOkResponse>(`${this.basePath}/person/${encodeURIComponent(String(personId))}/roles/${encodeURIComponent(String(roleId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * create new person
     * 
     * @param person 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPerson(person?: PersonInDto, observe?: 'body', reportProgress?: boolean): Observable<PersonResponse>;
    public createPerson(person?: PersonInDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonResponse>>;
    public createPerson(person?: PersonInDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonResponse>>;
    public createPerson(person?: PersonInDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PersonResponse>(`${this.basePath}/person`,
            person,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * delete person by id
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletePerson(id: number, observe?: 'body', reportProgress?: boolean): Observable<EmptyOkResponse>;
    public deletePerson(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmptyOkResponse>>;
    public deletePerson(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmptyOkResponse>>;
    public deletePerson(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deletePerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<EmptyOkResponse>(`${this.basePath}/person/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * add deny rule to place for person
     * 
     * @param personId 
     * @param placeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public denyPlaceForPerson(personId: number, placeId: number, observe?: 'body', reportProgress?: boolean): Observable<PersonAclResponse>;
    public denyPlaceForPerson(personId: number, placeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonAclResponse>>;
    public denyPlaceForPerson(personId: number, placeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonAclResponse>>;
    public denyPlaceForPerson(personId: number, placeId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling denyPlaceForPerson.');
        }

        if (placeId === null || placeId === undefined) {
            throw new Error('Required parameter placeId was null or undefined when calling denyPlaceForPerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<PersonAclResponse>(`${this.basePath}/person/${encodeURIComponent(String(personId))}/deny/${encodeURIComponent(String(placeId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * detach role from person
     * 
     * @param personId 
     * @param roleId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public detachRoleFromPerson(personId: number, roleId: number, observe?: 'body', reportProgress?: boolean): Observable<EmptyOkResponse>;
    public detachRoleFromPerson(personId: number, roleId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmptyOkResponse>>;
    public detachRoleFromPerson(personId: number, roleId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmptyOkResponse>>;
    public detachRoleFromPerson(personId: number, roleId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling detachRoleFromPerson.');
        }

        if (roleId === null || roleId === undefined) {
            throw new Error('Required parameter roleId was null or undefined when calling detachRoleFromPerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<EmptyOkResponse>(`${this.basePath}/person/${encodeURIComponent(String(personId))}/roles/${encodeURIComponent(String(roleId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get all personnel
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPersonnel(observe?: 'body', reportProgress?: boolean): Observable<AllPersonnelResponse>;
    public getAllPersonnel(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllPersonnelResponse>>;
    public getAllPersonnel(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllPersonnelResponse>>;
    public getAllPersonnel(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllPersonnelResponse>(`${this.basePath}/person`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get keys attached to person
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getKeysByPerson(id: number, observe?: 'body', reportProgress?: boolean): Observable<AllKeysResponse>;
    public getKeysByPerson(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllKeysResponse>>;
    public getKeysByPerson(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllKeysResponse>>;
    public getKeysByPerson(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getKeysByPerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllKeysResponse>(`${this.basePath}/person/${encodeURIComponent(String(id))}/keys`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get person by id
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPerson(id: number, observe?: 'body', reportProgress?: boolean): Observable<PersonResponse>;
    public getPerson(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonResponse>>;
    public getPerson(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonResponse>>;
    public getPerson(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getPerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PersonResponse>(`${this.basePath}/person/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get ACLs by person
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPersonACLs(id: number, observe?: 'body', reportProgress?: boolean): Observable<AllPersonAclsResponse>;
    public getPersonACLs(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllPersonAclsResponse>>;
    public getPersonACLs(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllPersonAclsResponse>>;
    public getPersonACLs(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getPersonACLs.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllPersonAclsResponse>(`${this.basePath}/person/${encodeURIComponent(String(id))}/acls`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get roles attached to person
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRolesByPerson(id: number, observe?: 'body', reportProgress?: boolean): Observable<AllRolesResponse>;
    public getRolesByPerson(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllRolesResponse>>;
    public getRolesByPerson(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllRolesResponse>>;
    public getRolesByPerson(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getRolesByPerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllRolesResponse>(`${this.basePath}/person/${encodeURIComponent(String(id))}/roles`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update person by id
     * 
     * @param id 
     * @param person 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePerson(id: number, person?: PersonInDto, observe?: 'body', reportProgress?: boolean): Observable<PersonResponse>;
    public updatePerson(id: number, person?: PersonInDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonResponse>>;
    public updatePerson(id: number, person?: PersonInDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonResponse>>;
    public updatePerson(id: number, person?: PersonInDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updatePerson.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<PersonResponse>(`${this.basePath}/person/${encodeURIComponent(String(id))}`,
            person,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
