/**
 * Jointbox access API
 * This is a API for access management for jointbox project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dmitriy.selischev@logicify.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AllPersonAclsResponse } from '../model/allPersonAclsResponse';
import { AllPlacesResponse } from '../model/allPlacesResponse';
import { AllRoleAclsResponse } from '../model/allRoleAclsResponse';
import { EmptyOkResponse } from '../model/emptyOkResponse';
import { PersonAclResponse } from '../model/personAclResponse';
import { PlaceInDto } from '../model/placeInDto';
import { PlaceResponse } from '../model/placeResponse';
import { RoleAclResponse } from '../model/roleAclResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PlacesService {

    protected basePath = 'http://jbaccess-server.herokuapp.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * add allow rule to place for person
     * 
     * @param personId 
     * @param placeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public allowPlaceForPerson(personId: number, placeId: number, observe?: 'body', reportProgress?: boolean): Observable<PersonAclResponse>;
    public allowPlaceForPerson(personId: number, placeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonAclResponse>>;
    public allowPlaceForPerson(personId: number, placeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonAclResponse>>;
    public allowPlaceForPerson(personId: number, placeId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling allowPlaceForPerson.');
        }

        if (placeId === null || placeId === undefined) {
            throw new Error('Required parameter placeId was null or undefined when calling allowPlaceForPerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<PersonAclResponse>(`${this.basePath}/person/${encodeURIComponent(String(personId))}/allow/${encodeURIComponent(String(placeId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * add allow rule to place for role
     * 
     * @param roleId 
     * @param placeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public allowPlaceForRole(roleId: number, placeId: number, observe?: 'body', reportProgress?: boolean): Observable<RoleAclResponse>;
    public allowPlaceForRole(roleId: number, placeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RoleAclResponse>>;
    public allowPlaceForRole(roleId: number, placeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RoleAclResponse>>;
    public allowPlaceForRole(roleId: number, placeId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (roleId === null || roleId === undefined) {
            throw new Error('Required parameter roleId was null or undefined when calling allowPlaceForRole.');
        }

        if (placeId === null || placeId === undefined) {
            throw new Error('Required parameter placeId was null or undefined when calling allowPlaceForRole.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<RoleAclResponse>(`${this.basePath}/role/${encodeURIComponent(String(roleId))}/allow/${encodeURIComponent(String(placeId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * attach door to place
     * 
     * @param placeId 
     * @param doorId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public attachDoorToPlace(placeId: number, doorId: number, observe?: 'body', reportProgress?: boolean): Observable<EmptyOkResponse>;
    public attachDoorToPlace(placeId: number, doorId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmptyOkResponse>>;
    public attachDoorToPlace(placeId: number, doorId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmptyOkResponse>>;
    public attachDoorToPlace(placeId: number, doorId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (placeId === null || placeId === undefined) {
            throw new Error('Required parameter placeId was null or undefined when calling attachDoorToPlace.');
        }

        if (doorId === null || doorId === undefined) {
            throw new Error('Required parameter doorId was null or undefined when calling attachDoorToPlace.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<EmptyOkResponse>(`${this.basePath}/places/${encodeURIComponent(String(placeId))}/doors/${encodeURIComponent(String(doorId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * create new place
     * 
     * @param place 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPlace(place?: PlaceInDto, observe?: 'body', reportProgress?: boolean): Observable<PlaceResponse>;
    public createPlace(place?: PlaceInDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PlaceResponse>>;
    public createPlace(place?: PlaceInDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PlaceResponse>>;
    public createPlace(place?: PlaceInDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PlaceResponse>(`${this.basePath}/places`,
            place,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * delete place by id
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletePlace(id: number, observe?: 'body', reportProgress?: boolean): Observable<EmptyOkResponse>;
    public deletePlace(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmptyOkResponse>>;
    public deletePlace(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmptyOkResponse>>;
    public deletePlace(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deletePlace.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<EmptyOkResponse>(`${this.basePath}/places/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * add deny rule to place for person
     * 
     * @param personId 
     * @param placeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public denyPlaceForPerson(personId: number, placeId: number, observe?: 'body', reportProgress?: boolean): Observable<PersonAclResponse>;
    public denyPlaceForPerson(personId: number, placeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonAclResponse>>;
    public denyPlaceForPerson(personId: number, placeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonAclResponse>>;
    public denyPlaceForPerson(personId: number, placeId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling denyPlaceForPerson.');
        }

        if (placeId === null || placeId === undefined) {
            throw new Error('Required parameter placeId was null or undefined when calling denyPlaceForPerson.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<PersonAclResponse>(`${this.basePath}/person/${encodeURIComponent(String(personId))}/deny/${encodeURIComponent(String(placeId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * add deny rule to place for role
     * 
     * @param roleId 
     * @param placeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public denyPlaceForRole(roleId: number, placeId: number, observe?: 'body', reportProgress?: boolean): Observable<RoleAclResponse>;
    public denyPlaceForRole(roleId: number, placeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RoleAclResponse>>;
    public denyPlaceForRole(roleId: number, placeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RoleAclResponse>>;
    public denyPlaceForRole(roleId: number, placeId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (roleId === null || roleId === undefined) {
            throw new Error('Required parameter roleId was null or undefined when calling denyPlaceForRole.');
        }

        if (placeId === null || placeId === undefined) {
            throw new Error('Required parameter placeId was null or undefined when calling denyPlaceForRole.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<RoleAclResponse>(`${this.basePath}/role/${encodeURIComponent(String(roleId))}/deny/${encodeURIComponent(String(placeId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * detach door from place
     * 
     * @param placeId 
     * @param doorId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public detachDoorFromPlace(placeId: number, doorId: number, observe?: 'body', reportProgress?: boolean): Observable<EmptyOkResponse>;
    public detachDoorFromPlace(placeId: number, doorId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmptyOkResponse>>;
    public detachDoorFromPlace(placeId: number, doorId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmptyOkResponse>>;
    public detachDoorFromPlace(placeId: number, doorId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (placeId === null || placeId === undefined) {
            throw new Error('Required parameter placeId was null or undefined when calling detachDoorFromPlace.');
        }

        if (doorId === null || doorId === undefined) {
            throw new Error('Required parameter doorId was null or undefined when calling detachDoorFromPlace.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<EmptyOkResponse>(`${this.basePath}/places/${encodeURIComponent(String(placeId))}/doors/${encodeURIComponent(String(doorId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get all places
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPlaces(observe?: 'body', reportProgress?: boolean): Observable<AllPlacesResponse>;
    public getAllPlaces(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllPlacesResponse>>;
    public getAllPlaces(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllPlacesResponse>>;
    public getAllPlaces(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllPlacesResponse>(`${this.basePath}/places`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get doors attached to place
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDoorsByPlace(id: number, observe?: 'body', reportProgress?: boolean): Observable<AllPlacesResponse>;
    public getDoorsByPlace(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllPlacesResponse>>;
    public getDoorsByPlace(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllPlacesResponse>>;
    public getDoorsByPlace(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getDoorsByPlace.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllPlacesResponse>(`${this.basePath}/places/${encodeURIComponent(String(id))}/doors`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get ACLs by person
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPersonACLs(id: number, observe?: 'body', reportProgress?: boolean): Observable<AllPersonAclsResponse>;
    public getPersonACLs(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllPersonAclsResponse>>;
    public getPersonACLs(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllPersonAclsResponse>>;
    public getPersonACLs(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getPersonACLs.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllPersonAclsResponse>(`${this.basePath}/person/${encodeURIComponent(String(id))}/acls`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get place by id
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPlace(id: number, observe?: 'body', reportProgress?: boolean): Observable<PlaceResponse>;
    public getPlace(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PlaceResponse>>;
    public getPlace(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PlaceResponse>>;
    public getPlace(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getPlace.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PlaceResponse>(`${this.basePath}/places/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get ACLs by role
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRoleACLs(id: number, observe?: 'body', reportProgress?: boolean): Observable<AllRoleAclsResponse>;
    public getRoleACLs(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllRoleAclsResponse>>;
    public getRoleACLs(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllRoleAclsResponse>>;
    public getRoleACLs(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getRoleACLs.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AllRoleAclsResponse>(`${this.basePath}/role/${encodeURIComponent(String(id))}/acls`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update place by id
     * 
     * @param id 
     * @param place 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePlace(id: number, place?: PlaceInDto, observe?: 'body', reportProgress?: boolean): Observable<PlaceResponse>;
    public updatePlace(id: number, place?: PlaceInDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PlaceResponse>>;
    public updatePlace(id: number, place?: PlaceInDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PlaceResponse>>;
    public updatePlace(id: number, place?: PlaceInDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updatePlace.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<PlaceResponse>(`${this.basePath}/places/${encodeURIComponent(String(id))}`,
            place,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
